name: 2 jobs one PSE

on:
  workflow_dispatch:

jobs:
  install-node-deps:
    name: Install npm dependencies
    runs-on: ubuntu-latest

    steps:
        # ============= InvisiRisk Setup =============
      - name: Setup PSE
        uses:  invisirisk/pse-action@develop
        with:
          api_url: "https://app.stage.invisirisk.com"
          app_token: 38-lV3dwtbDVNp9HAOs_Q4nZBVnqlmTNduRNFFAJh1sS3XJomrAmgVqSS6C6oZgaEfPbwaJAlwaopwX-J94RYA
          debug: true
      # ============= InvisiRisk Setup End =============
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
        

      - name: Install random npm package
        run: npm install lodash

      # - name: Intentional failure
      #   run: exit 1
      
      - name: Curl Google
        run: curl -I https://www.google.com

  install-python-package:
    name: Install PyPI package
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install random PyPI package
        run: pip install requests

      - name: Curl Google
        run: curl -I https://www.google.com

