name: http 8000 port

on:
  workflow_dispatch:

jobs:
  curl-test:
    runs-on: ubuntu-latest
    steps:
      # ============= InvisiRisk Setup =============
      - name: Setup PSE
        uses: invisirisk/pse-action@latest
        with:
          api_url: "https://app.stage.invisirisk.com"
          app_token: n2HzcVLlGbmJoDYBPZROObvToZjnomhCp7MO34kLKnbWLfkgsoUm04gjEXl9OBnO5mXUE7Xm-22iralY9mDLCw
          mode: "sidecar"
      # ============= InvisiRisk Setup End =============
      - name: Curl test (port 8000 + path)
        run: |
          curl -v -k https://praneshdhunjushresthathatdoesnotexist.com
